Speisekarte/Models/ErrorViewModel.cs
namespace Speisekarte.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Speisekarte/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Speisekarte.Data;
using Speisekarte.Models;
using SQLitePCL;
using System.Diagnostics;
using System.Globalization;

namespace Speisekarte.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            string day = DateTimeFormatInfo.CurrentInfo.GetDayName(DateTime.Now.DayOfWeek);
            ViewData["TagesHit"] = $"Heute, am {day}, gibt es eine scharfe Soße gratis dazu";

            List<SelectListItem> selectListItems= new List<SelectListItem>();
            SelectListItem eintrag = new SelectListItem("Top", "3");
            selectListItems.Add(eintrag);
            SelectListItem eintrag2 = new SelectListItem("Medium", "2");
            selectListItems.Add(eintrag2);
            SelectListItem eintrag3 = new SelectListItem("Low", "1");
            selectListItems.Add(eintrag3);

            ViewData["Kategorien"] = selectListItems;

            var speisen = _context.Speisen.Include(speise => speise.Zutaten).ToList();
            return View(speisen);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult GetSpeisenPartial(string query)
        {
            List<Speise> speisen = new List<Speise>();

            if (string.IsNullOrEmpty(query))
            {
                speisen = _context.Speisen.Include(speise => speise.Zutaten).ToList();
            }
            else
            {
                speisen = _context.Speisen.Where(x => x.Titel.ToLower().Contains(query.ToLower())).Include(speise => speise.Zutaten).ToList();
            }
            return PartialView("index",speisen);
        }

        public IActionResult DeleteSpeise(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var speiseFromDB = _context.Speisen.Include(speise => speise.Zutaten).SingleOrDefault(x => x.Id == id);
            if (speiseFromDB is null)
            {
                return NotFound();
            }

            foreach (var zutat in speiseFromDB.Zutaten)
            {
                _context.Zutaten.Remove(zutat);
            }

            _context.Speisen.Remove(speiseFromDB);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Speisekarte/Controllers/SpeiseKarteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Speisekarte.Data;
using Speisekarte.Models;

namespace Speisekarte.Controllers
{
    public class SpeiseKarteController : Controller
    {
        private ApplicationDbContext _context;

        public SpeiseKarteController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var speisen = _context.Speisen.Include(speise => speise.Zutaten).ToList();
            return View();
        }

        public IActionResult CreateSpeiseForm()
        {
            //// Informationen für eine Drop-Down-Liste bereitstellen
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            SelectListItem eintrag1 = new SelectListItem("Yummy Good", "5");
            selectListItems.Add(eintrag1);
            SelectListItem eintrag2 = new SelectListItem("Good", "4");
            selectListItems.Add(eintrag2);
            SelectListItem eintrag3 = new SelectListItem("Nice", "3");
            selectListItems.Add(eintrag3);
            SelectListItem eintrag4 = new SelectListItem("Ok", "2");
            selectListItems.Add(eintrag4);
            SelectListItem eintrag5 = new SelectListItem("Awful", "1");
            selectListItems.Add(eintrag5);

            // Die Übergabe erfolgt über das ViewData-Dictionary
            ViewData["Kategorien"] = selectListItems;

            return View();
        }

        public IActionResult AddZutatForm(int? id)
        {
            if (id is not null && id > 0)
            {
                var speisenFromDB = _context.Speisen.FirstOrDefault(s => s.Id == id);
                if (speisenFromDB is not null)
                {
                    Zutat zutat = new Zutat();
                    zutat.SpeiseId = id;
                    return View(zutat);
                }
            }
            return View();
        }

        public IActionResult AddZutat(Zutat zutat)
        {
            if (zutat.SpeiseId is not null && zutat.SpeiseId > 0)
            {
                Speise? speisenFromDB = _context.Speisen.FirstOrDefault(x => x.Id == zutat.SpeiseId);
                if (speisenFromDB is not null)
                {
                    speisenFromDB.Zutaten.Add(zutat);
                    _context.SaveChanges();
                }
            }
            return View("Index");
        }

        public IActionResult CreateEditSpeiseListe(Speise speise)
        {
            if (speise.Id == 0)
            {
                _context.Speisen.Add(speise);
            }
            else
            {
                var geschenkFromDB = _context.Speisen.Include(speise => speise.Zutaten).SingleOrDefault(x => x.Id == speise.Id);
                if (geschenkFromDB == null)
                {
                    return NotFound();
                }
                else
                {
                    geschenkFromDB.Titel = speise.Titel;
                    geschenkFromDB.Notizen = speise.Notizen;
                    geschenkFromDB.Sterne = speise.Sterne;
                    geschenkFromDB.Zutaten = speise.Zutaten;
                }
            }

            _context.SaveChanges();

            return View("Index");
        }
    }
}

Speisekarte/Controllers/SpeisenController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Speisekarte.Data;
using SQLitePCL;
using System.Net.WebSockets;

namespace Speisekarte.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SpeisenController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public SpeisenController(ApplicationDbContext context)
        {
            _context = context;
        }


        [HttpPost]
        [Route("Fill")]
        public void FillData()
        {
            Speise s1 = new Speise { Titel = "Hauptspeise", Notizen = "Meine Notizen dazu", Sterne = 5 };
            Zutat z1 = new Zutat { Beschreibung = "Mehl", Einheit = "gramm", Menge = 200 };
            Zutat z2 = new Zutat { Beschreibung = "Zucker", Einheit = "gramm", Menge = 50 };
            Zutat z3 = new Zutat { Beschreibung = "Öl", Einheit = "ml", Menge = 100 };

            s1.Zutaten.Add(z1);
            s1.Zutaten.Add(z2);
            s1.Zutaten.Add(z3);

            _context.Speisen.Add(s1);
            _context.SaveChanges();
        }


        [HttpGet]
        [Route("Getall")]
        public List<Speise> GetSpeisen()
        {
            var speisen = _context.Speisen
                .Include(speise => speise.Zutaten)
                .ToList();
            return speisen;
        }

        [HttpDelete("Delete")]
        public async Task<IActionResult> Delete(int? id) 
        {
            if(id == null || _context.Speisen == null)
            {
                return NotFound();
            }

            var speise = await _context.Speisen.Include(speise => speise.Zutaten).SingleOrDefaultAsync(s => s.Id == id);

            if(speise == null)
            {
                return NotFound();
            }
            
            foreach(var zutat in speise.Zutaten)
            {
                _context.Zutaten.Remove(zutat);
            }

            _context.Speisen.Remove(speise);

            await _context.SaveChangesAsync();

            return Ok();
        }
    }
}

Speisekarte/Views/Home/Index.cshtml
@using Speisekarte.Data;
@model List<Speise>

@{
    ViewData["Title"] = "Home Page";
}

<h1 style="text-align:center">SpeiseKarte</h1>
<h4 style="text-align:center">Spezialangebot des Tages: @ViewData["TagesHit"]</h4>

<hr />
@if(ViewData["Kategorien"] is not null)
{
    var elem = ViewData["Kategorien"] as IEnumerable<SelectListItem>;
    if(elem is not null)
    {
        foreach(var n in elem)
        {
            <li>@n.Text ist @n.Value</li>
        }
        <br />
        <label class="control-label">Kategorien: </label>
        <select form-control" asp-items="elem"></select>
    }
}
<br />
<hr />

<table id="SpeisenTable" class="table table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <td>Titel</td>
            <td>Notiz</td>
            <td>Sterne</td>
            <td>Zutaten</td>
            <td>Löschen</td>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (Speise speise in Model)
            {
                <tr>
                    <td>@speise.Titel</td>
                    <td>@speise.Notizen</td>
                    <td>
                        @for(int i=0; i < @speise.Sterne; i++){
                            <span>🟊</span>
                        }
                    </td>
                    <td>
                    <ul>
                    @for (int i = 0; i < speise.Zutaten.Count; i++)
                    {
                        <li>@speise.Zutaten[i]</li>
                    }
                    </ul>
                    </td>
                    @*<td><a asp-route-id="@speise.Id" asp-controller="Home" asp-action="DeleteSpeise" class="btn btn-danger">Delete</a></td>*@
                    <td><button type="button" class="btn btn-danger" onclick="onDeleteClicked(@speise.Id)">Delete</button></td>
                </tr>
            }
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Löschen bestätigen</h5>
                <button type="button" class="btn btn-close close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Wollen Sie wirklich löschen?
            </div>
            <div class="modal-footer">                
                <button type="button" class="btn btn-success ok">Ja</button>
                <button type="button" class="btn btn-default cancel" data-dismiss="modal">Nein</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        function onDeleteClicked(id) {
            //Frage den Benutzer...

            $('#confirmDelete').modal('show');

            $('#confirmDelete .modal-footer .ok').on('click', function () {
                //Backend Call
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteSpeise")",
                    data: { id: id },
                    success: function (msg) {
                        //alert("Ok, wurde gelöscht");
                        location.reload();
                    },
                    error: function (msg) {
                        alert("Fehler beim Löschen");
                    }
                });
                $('#confirmDelete').modal('hide');
            });
            $('#confirmDelete .modal-footer .cancel').on('click', function () {
                $('#confirmDelete').modal('hide');
            });
            $('#confirmDelete .modal-header .close').on('click', function () {
                $('#confirmDelete').modal('hide');
            });
        }
    </script>
}

Speisekarte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Speisekarte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Speisekarte.styles.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Speisekarte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <a class="nav-link text-dark" asp-controller="SpeiseKarte" asp-action="CreateSpeiseForm">Speise Erstellung</a>
                <a class="nav-link text-dark" asp-controller="SpeiseKarte" asp-action="AddZutatForm">Zutat Erstellung</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Speisekarte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Speisekarte/Views/SpeiseKarte/AddZutatForm.cshtml
@model Zutat;
@using Speisekarte.Data;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="SpeiseKarte" asp-action="AddZutat" enctype="multipart/form-data">
    <div class="card">
        <div class="card-header">
            <h1>Hier werden Zutaten hinzugefügt!</h1>
        </div>
        <div class="card-body">
            <input hidden asp-for="SpeiseId" />

            <div class="row mb-3">
                <div class="col">
                    <label>Wie heißt die Zutat?</label>
                    <input class="form-control" asp-for="Beschreibung" type="text" placeholder="Zutat" />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label>In welcher Einheit soll die Menge dargestellt werden (g/kg/l/ml/...)?</label>
                    <input class="form-control" asp-for="Einheit" type="text" placeholder="Einheit" />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label>Wie viel soll von der Zutat verwendet werden?</label>
                    <input class="form-control" asp-for="Menge" type="number" step="0.1" placeholder="Menge" />
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Hinzufügen</button>
        </div>
    </div>

</form>

Speisekarte/Views/SpeiseKarte/CreateSpeiseForm.cshtml
@model Speise
@using Speisekarte.Data;


<div class="container">
    <form asp-controller="SpeiseKarte" asp-action="CreateEditSpeiseListe" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h1>Neue Speise erstellen</h1>
            </div>
            <div class="card-body">
                <input hidden asp-for="Id" />

                <div class="row mb-3">
                    <div class="col">
                        <label>Welche Speise möchten hinzufügen?</label>
                        <input class="form-control" asp-for="Titel" type="text" placeholder="Speise" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label>Notizen (z.B. wie die Speise zubereitet wird)</label>
                        <textarea class="form-control" asp-for="Notizen" type="text" placeholder="Schritt 1: Kartoffel schneiden..."></textarea>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <select asp-for="Sterne" form-control" asp-items="@((IEnumerable<SelectListItem>)ViewData["Kategorien"])"></select>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Hinzufügen</button>
            </div>
        </div>

    </form>
</div>

Speisekarte/Views/SpeiseKarte/Index.cshtml
@model Speise
@using Speisekarte.Data;
@{
    ViewData["Title"] = "Index";
}

<form asp-controller="SpeiseKarte" asp-action="CreateEditSpeiseListe" enctype="multipart/form-data">
    <div class="card">
        <div class="card-header">
            Geschenke bearbeiten
        </div>
        <div class="card-body">
            <input hidden asp-for="Id" />

            Speise:
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="Titel" type="text" placeholder="Speisen Name" />
                </div>
            </div>

            Notizen:
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="Notizen" type="text" placeholder="Notizen" />
                </div>
            </div>

            Sterne:
            <div class="row mb-3">
                <div class="col">
                    @*<input class="form-control" asp-for="Sterne" type="number" placeholder="Sterne" max="3"/>*@
                    <select asp-for="Sterne" form-control" asp-items="@((IEnumerable<SelectListItem>)ViewData["Kategorien"])"></select>
                </div>
            </div>

            Zutaten:
            <div id="zutaten-container">
                <div class="row mb-3 zutaten-row">
                    <div class="col">
                        <input class="form-control" asp-for="Zutaten[0].Beschreibung" placeholder="Beschreibung" />
                    </div>
                    <div class="col">
                        <input class="form-control" asp-for="Zutaten[0].Einheit" placeholder="Einheit" />
                    </div>
                    <div class="col">
                        <input class="form-control" asp-for="Zutaten[0].Menge" placeholder="Menge" />
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-danger remove-zutat">Entfernen</button>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-secondary" id="add-zutat">Weitere Zutat hinzufügen</button>

        </div>

        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        var zutatIndex = 0;

        $('#add-zutat').click(function () {
            zutatIndex++;
            var row = $('.zutaten-row').first().clone();
            row.find('input').each(function () {
                var newName = $(this).attr('name').replace('[0]', '[' + zutatIndex + ']');
                $(this).attr('name', newName);
                $(this).val('');
            });
            $('#zutaten-container').append(row);
        });

        $(document).on('click', '.remove-zutat', function () {
            $(this).closest('.zutaten-row').remove();
            zutatIndex--;
        });
    });
</script>